# Generated by Django 5.2.3 on 2025-06-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('static_path', models.CharField(max_length=200)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'About Image',
                'verbose_name_plural': 'About Image',
            },
        ),
        migrations.CreateModel(
            name='ProjectCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=100)),
                ('project_path', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Project Card',
                'verbose_name_plural': 'Project Cards',
            },
        ),
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicename', models.CharField(max_length=100)),
                ('service_path', models.CharField(max_length=200)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Service Card',
                'verbose_name_plural': 'Service Cards',
                'ordering': ['order'],
            },
        ),
    ]
