# Generated by Django 5.2.3 on 2025-06-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_webdevprojectcard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webdevprojectcard',
            options={'verbose_name': 'Web Dev Project Card', 'verbose_name_plural': 'Web Dev Project Card'},
        ),
        migrations.AddField(
            model_name='servicecard',
            name='link',
            field=models.CharField(default='#', max_length=100),
        ),
    ]
