# Generated by Django 5.2.3 on 2025-06-23 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_appdevprojectcard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appdevprojectcard',
            options={'verbose_name': 'App Dev Project Card', 'verbose_name_plural': 'App Dev Project Card'},
        ),
    ]
