# Generated by Django 5.2.3 on 2025-06-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_appdevprojectcard_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PythonDevProjectCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=100)),
                ('project_path', models.CharField(max_length=200)),
                ('link', models.CharField(default='#', max_length=200)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Python Dev Project Card',
                'verbose_name_plural': 'Python Dev Project Card',
            },
        ),
    ]
