# Generated by Django 5.2.3 on 2025-06-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_pythondevprojectcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='UIUXProjectCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=100)),
                ('project_path', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'UI/UX Project Card',
                'verbose_name_plural': 'UI/UX Project Card',
            },
        ),
    ]
