# Generated by Django 5.2.3 on 2025-06-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_uiuxprojectcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchivementCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.CharField(default='#', max_length=200)),
            ],
            options={
                'verbose_name': 'Achievement Card',
                'verbose_name_plural': 'Achievement Cards',
            },
        ),
        migrations.CreateModel(
            name='AchivementCardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.CharField(default='#', max_length=200)),
            ],
            options={
                'verbose_name': 'Achievement Card',
                'verbose_name_plural': 'Achievement Cards',
            },
        ),
    ]
