# Generated by Django 5.2.3 on 2025-06-25 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_achivementcard_achivementcardmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achivementcardmodel',
            options={'verbose_name': 'Achievement Card Model', 'verbose_name_plural': 'Achievement Cards Model'},
        ),
    ]
