# Generated by Django 5.2.3 on 2025-06-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_achivementcardmodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('cataegory', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link', models.CharField(default='#', max_length=200)),
                ('badge', models.CharField(default='#', max_length=200)),
                ('badge2', models.CharField(default='#', max_length=200)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
            },
        ),
    ]
