# Generated by Django 5.2.3 on 2025-07-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('cataegory', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link', models.CharField(default='#', max_length=200)),
            ],
            options={
                'verbose_name': 'Blogs',
                'verbose_name_plural': 'Blogs Posts',
            },
        ),
    ]
