# Generated by Django 5.2.3 on 2026-05-13 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('web', 'Web Services'), ('seo', 'SEO'), ('photo', 'Photography'), ('app', 'App Development')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('monthly_price', models.IntegerField()),
                ('yearly_price', models.IntegerField()),
                ('button_type', models.CharField(default='ghost', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=20)),
                ('tier', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=20)),
                ('tag', models.CharField(max_length=50)),
                ('emoji', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='services/')),
                ('perk1', models.CharField(max_length=200)),
                ('perk2', models.CharField(max_length=200)),
                ('perk3', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='home.servicecategory')),
            ],
        ),
    ]
